dist: xenial

branches: 
  only:
    - master
    - dev

env:
  - PSQLCONN=postgresql://postgres:@localhost:5432/travis_ci_test

git:
  depth: 1

notifications:
  email: false
  webhooks:
    - https://hooks.slack.com/services/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

services:
  - postgresql
  - mongodb

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - psql -U postgres -d travis_ci_test -c "CREATE TABLE fun (cool int, verycool int);"
  - psql -U postgres -d travis_ci_test -c "INSERT INTO fun (cool, verycool) VALUES (55, 888);"
  - git config --global url."https://361b27e50c931664bbb8494e6092b396790c7d55:x-oauth-basic@github.com/".insteadOf https://github.com

matrix: 
  include:
    - language: go
      go:
        - 1.12.x
      script:
      - go test
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
      - npm test