dist: xenial

branches: 
  only:
    - master
    - dev

git:
  depth: 1

notifications:
  email: false


matrix: 
  include:
    - language: go
      go:
        - 1.12.x
      script:
      - go test
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
      - npm test