dist: xenial

branches: 
  only:
    - master
    - dev

git:
  depth: 1

notifications:
  email: false
  webhooks:
    - https://hooks.slack.com/services/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

matrix: 
  include:
    - language: go
      go:
        - 1.12.x
      script:
      - go test
    - language: node_js
      node_js:
        - "stable"
      cache:
        directories:
        - node_modules
      script:
      - npm test